### ISSUE TITLE
Get rid of OpenCV dependancy

### ISSUE THREAD

**Issue by alexklibisz** [alexklibisz/tensortube#4]
Right now we are only using OpenCV in one place... the actual video partitioning is done with the imageio library. This is because I had trouble getting OpenCV to run on the EC2 instance. I think imageio is a much simpler library to use and install, so it would be preferable if OpenCV can get replaced.

**Comment by grantbruer** [comment]
Fixed. We're now using imageio to get the image in jpeg format.
