### ISSUE TITLE
where to get pre-trained models

### ISSUE THREAD

**Issue by IamMegatron2025** [alexklibisz/tensortube#9]
hello, Is your code for video classification? and can you provide some pre-trained models?
thank you very much..

**Comment by alexklibisz** [comment]
It's for image classification, where the images are frames from a video.

We built it based on this tutorial: https://www.tensorflow.org/tutorials/image_recognition. They provide the pre-trained weights.

**Comment by IamMegatron2025** [comment]
@alexklibisz so can it use video as a input?

**Comment by alexklibisz** [comment]
@IvyGongoogle It breaks the video into individual frames (jpeg files) and then does image classification on each of the frames.

**Comment by IamMegatron2025** [comment]
@alexklibisz Ok，I see. Thank you

**Comment by IamMegatron2025** [comment]
close this issue
